# @file ~/.config/mise/settings.toml
# ref:
# https://mise.jdx.dev/configuration.html#settings-file-config-mise-settings-toml

jobs = 4            # number of plugins or runtimes to install in parallel. The default is `4`.
experimental = true # enable experimental features